resolver: lts-7.7

packages:
- '.'
- location:
    git: https://github.com/oisdk/mddoctest.git
    commit: d105da84caee5c3d1eb8ed12430dfb797b878480

extra-deps:
- hakyll-4.9.0.0
- hakyll-series-0.1.0.1

flags: {}
extra-package-dbs: []
