resolver: lts-5.18

packages:
- '.'
- location:
    git: https://github.com/oisdk/mddoctest.git
    commit: d105da84caee5c3d1eb8ed12430dfb797b878480
- location:
    git: https://github.com/oisdk/hakyll-series.git
    commit: 01060e7d2d06e31e19c920951e054be6635102ba

extra-deps: []

flags: {}
extra-package-dbs: []
